ci:
  assert:
    assertions:
      categories:accessibility: [error, minScore: 0.96]
      categories:best-practices: [error, minScore: 1]
      categories:performance: [error, minScore: 0.66]
      categories:seo: [error, minScore: 0.92]
    includePassedAssertions: true
  collect:
    numberOfRuns: 1
    startServerCommand: ws
    startServerReadyPattern: Listening on
    url:
      - http://localhost:8080/en
  upload:
    outputDir: .lighthouseci/results
    target: filesystem
